import Button from 'Components/Shared/Button';
import Spinner from 'Components/Shared/Spinner';
import { useSelector } from 'react-redux';
import styles from './availability.module.css';
import { useState } from 'react';

function AvailabilityForm({ handleSubmit, handleShowModal }) {
  const postulant = useSelector((store) => store.postulantModule.postulantData);
  const isLoadingForm = useSelector((store) => store.postulants.isLoadingForm);
  const [array, setArray] = useState([]);

  const onSubmit = () => {
    postulant.availability = array;
    handleSubmit(postulant);
    handleShowModal(false);
  };
  const handleChange = (e) => {
    if (e.target.checked) {
      setArray([
        ...array,
        {
          key: e.target.value,
          day: e.target.value.split('-')[0],
          time: `${e.target.value.split('-')[1]}:00`
        }
      ]);
    } else {
      setArray((prevState) => prevState.filter((item) => item.key !== e.target.value));
    }
  };
  const isChecked = (key) => {
    return array?.some((element) => element.key === key);
  };
  if (isLoadingForm) return <Spinner type="ThreeDots" color="#002147" height={80} width={80} />;

  return (
    <section>
      <div>
        <h2 className={styles.title}>
          <span className={styles.bold}>Availability</span>
        </h2>
        <table border="1" className={styles.tableSummary}>
          <thead>
            <tr>
              <td>Day</td>
              <td>Monday</td>
              <td>Tuesday</td>
              <td>Wednesday</td>
              <td>Thursday</td>
              <td>Friday</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>06:00</td>
              <td>
                <input
                  key="1"
                  type="checkbox"
                  id="monday-06"
                  value="monday-06"
                  onChange={handleChange}
                  checked={isChecked('monday-06')}
                />
              </td>
              <td>
                <input
                  key="2"
                  type="checkbox"
                  id="tuesday-06"
                  value="tuesday-06"
                  onChange={handleChange}
                  checked={isChecked('tuesday-06')}
                />
              </td>
              <td>
                <input
                  key="3"
                  type="checkbox"
                  id="wednesday-06"
                  value="wednesday-06"
                  onChange={handleChange}
                  checked={isChecked('wednesday-06')}
                />
              </td>
              <td>
                <input
                  key="4"
                  type="checkbox"
                  id="thursday-06"
                  value="thursday-06"
                  onChange={handleChange}
                  checked={isChecked('thursday-06')}
                />
              </td>
              <td>
                <input
                  key="5"
                  type="checkbox"
                  id="friday-06"
                  value="friday-06"
                  onChange={handleChange}
                  checked={isChecked('friday-06')}
                />
              </td>
            </tr>
            <tr>
              <td>07:00</td>
              <td>
                <input
                  key="6"
                  type="checkbox"
                  id="monday-07"
                  value="monday-07"
                  onChange={handleChange}
                  checked={isChecked('monday-07')}
                />
              </td>
              <td>
                <input
                  key="7"
                  type="checkbox"
                  id="tuesday-07"
                  value="tuesday-07"
                  onChange={handleChange}
                  checked={isChecked('tuesday-07')}
                />
              </td>
              <td>
                <input
                  key="8"
                  type="checkbox"
                  id="wednesday-07"
                  value="wednesday-07"
                  onChange={handleChange}
                  checked={isChecked('wednesday-07')}
                />
              </td>
              <td>
                <input
                  key="9"
                  type="checkbox"
                  id="thursday-07"
                  value="thursday-07"
                  onChange={handleChange}
                  checked={isChecked('thursday-07')}
                />
              </td>
              <td>
                <input
                  key="10"
                  type="checkbox"
                  id="friday-07"
                  value="friday-07"
                  onChange={handleChange}
                  checked={isChecked('friday-07')}
                />
              </td>
            </tr>
            <tr>
              <td>08:00</td>
              <td>
                <input
                  key="11"
                  type="checkbox"
                  id="monday-08"
                  value="monday-08"
                  onChange={handleChange}
                  checked={isChecked('monday-08')}
                />
              </td>
              <td>
                <input
                  key="12"
                  type="checkbox"
                  id="tuesday-08"
                  value="tuesday-08"
                  onChange={handleChange}
                  checked={isChecked('tuesday-08')}
                />
              </td>
              <td>
                <input
                  key="13"
                  type="checkbox"
                  id="wednesday-08"
                  value="wednesday-08"
                  onChange={handleChange}
                  checked={isChecked('wednesday-08')}
                />
              </td>
              <td>
                <input
                  key="14"
                  type="checkbox"
                  id="thursday-08"
                  value="thursday-08"
                  onChange={handleChange}
                  checked={isChecked('thursday-08')}
                />
              </td>
              <td>
                <input
                  key="15"
                  type="checkbox"
                  id="friday-08"
                  value="friday-08"
                  onChange={handleChange}
                  checked={isChecked('friday-08')}
                />
              </td>
            </tr>
            <tr>
              <td>09:00</td>
              <td>
                <input
                  key="16"
                  type="checkbox"
                  id="monday-09"
                  value="monday-09"
                  onChange={handleChange}
                  checked={isChecked('monday-09')}
                />
              </td>
              <td>
                <input
                  key="17"
                  type="checkbox"
                  id="tuesday-09"
                  value="tuesday-09"
                  onChange={handleChange}
                  checked={isChecked('tuesday-09')}
                />
              </td>
              <td>
                <input
                  key="18"
                  type="checkbox"
                  id="wednesday-09"
                  value="wednesday-09"
                  onChange={handleChange}
                  checked={isChecked('wednesday-09')}
                />
              </td>
              <td>
                <input
                  key="19"
                  type="checkbox"
                  id="thursday-09"
                  value="thursday-09"
                  onChange={handleChange}
                  checked={isChecked('thursday-09')}
                />
              </td>
              <td>
                <input
                  key="20"
                  type="checkbox"
                  id="friday-09"
                  value="friday-09"
                  onChange={handleChange}
                  checked={isChecked('friday-09')}
                />
              </td>
            </tr>
            <tr>
              <td>10:00</td>
              <td>
                <input
                  key="21"
                  type="checkbox"
                  id="monday-10"
                  value="monday-10"
                  onChange={handleChange}
                  checked={isChecked('monday-10')}
                />
              </td>
              <td>
                <input
                  key="22"
                  type="checkbox"
                  id="tuesday-10"
                  value="tuesday-10"
                  onChange={handleChange}
                  checked={isChecked('tuesday-10')}
                />
              </td>
              <td>
                <input
                  key="23"
                  type="checkbox"
                  id="wednesday-10"
                  value="wednesday-10"
                  onChange={handleChange}
                  checked={isChecked('wednesday-10')}
                />
              </td>
              <td>
                <input
                  key="24"
                  type="checkbox"
                  id="thursday-10"
                  value="thursday-10"
                  onChange={handleChange}
                  checked={isChecked('thursday-10')}
                />
              </td>
              <td>
                <input
                  key="25"
                  type="checkbox"
                  id="friday-10"
                  value="friday-10"
                  onChange={handleChange}
                  checked={isChecked('friday-10')}
                />
              </td>
            </tr>
            <tr>
              <td>11:00</td>
              <td>
                <input
                  key="26"
                  type="checkbox"
                  id="monday-11"
                  value="monday-11"
                  onChange={handleChange}
                  checked={isChecked('monday-11')}
                />
              </td>
              <td>
                <input
                  key="27"
                  type="checkbox"
                  id="tuesday-11"
                  value="tuesday-11"
                  onChange={handleChange}
                  checked={isChecked('tuesday-11')}
                />
              </td>
              <td>
                <input
                  key="28"
                  type="checkbox"
                  id="wednesday-11"
                  value="wednesday-11"
                  onChange={handleChange}
                  checked={isChecked('wednesday-11')}
                />
              </td>
              <td>
                <input
                  key="29"
                  type="checkbox"
                  id="thursday-11"
                  value="thursday-11"
                  onChange={handleChange}
                  checked={isChecked('thursday-11')}
                />
              </td>
              <td>
                <input
                  key="30"
                  type="checkbox"
                  id="friday-11"
                  value="friday-11"
                  onChange={handleChange}
                  checked={isChecked('friday-11')}
                />
              </td>
            </tr>
            <tr>
              <td>12:00</td>
              <td>
                <input
                  key="31"
                  type="checkbox"
                  id="monday-12"
                  value="monday-12"
                  onChange={handleChange}
                  checked={isChecked('monday-12')}
                />
              </td>
              <td>
                <input
                  key="32"
                  type="checkbox"
                  id="tuesday-12"
                  value="tuesday-12"
                  onChange={handleChange}
                  checked={isChecked('tuesday-12')}
                />
              </td>
              <td>
                <input
                  key="33"
                  type="checkbox"
                  id="wednesday-12"
                  value="wednesday-12"
                  onChange={handleChange}
                  checked={isChecked('wednesday-12')}
                />
              </td>
              <td>
                <input
                  key="34"
                  type="checkbox"
                  id="thursday-12"
                  value="thursday-12"
                  onChange={handleChange}
                  checked={isChecked('thursday-12')}
                />
              </td>
              <td>
                <input
                  key="35"
                  type="checkbox"
                  id="friday-12"
                  value="friday-12"
                  onChange={handleChange}
                  checked={isChecked('friday-12')}
                />
              </td>
            </tr>
            <tr>
              <td>13:00</td>
              <td>
                <input
                  key="36"
                  type="checkbox"
                  id="monday-13"
                  value="monday-13"
                  onChange={handleChange}
                  checked={isChecked('monday-13')}
                />
              </td>
              <td>
                <input
                  key="37"
                  type="checkbox"
                  id="tuesday-13"
                  value="tuesday-13"
                  onChange={handleChange}
                  checked={isChecked('tuesday-13')}
                />
              </td>
              <td>
                <input
                  key="38"
                  type="checkbox"
                  id="wednesday-13"
                  value="wednesday-13"
                  onChange={handleChange}
                  checked={isChecked('wednesday-13')}
                />
              </td>
              <td>
                <input
                  key="39"
                  type="checkbox"
                  id="thursday-13"
                  value="thursday-13"
                  onChange={handleChange}
                  checked={isChecked('thursday-13')}
                />
              </td>
              <td>
                <input
                  key="40"
                  type="checkbox"
                  id="friday-13"
                  value="friday-13"
                  onChange={handleChange}
                  checked={isChecked('friday-13')}
                />
              </td>
            </tr>
            <tr>
              <td>14:00</td>
              <td>
                <input
                  key="41"
                  type="checkbox"
                  id="monday-14"
                  value="monday-14"
                  onChange={handleChange}
                  checked={isChecked('monday-14')}
                />
              </td>
              <td>
                <input
                  key="42"
                  type="checkbox"
                  id="tuesday-14"
                  value="tuesday-14"
                  onChange={handleChange}
                  checked={isChecked('tuesday-14')}
                />
              </td>
              <td>
                <input
                  key="43"
                  type="checkbox"
                  id="wednesday-14"
                  value="wednesday-14"
                  onChange={handleChange}
                  checked={isChecked('wednesday-14')}
                />
              </td>
              <td>
                <input
                  key="44"
                  type="checkbox"
                  id="thursday-14"
                  value="thursday-14"
                  onChange={handleChange}
                  checked={isChecked('thursday-14')}
                />
              </td>
              <td>
                <input
                  key="45"
                  type="checkbox"
                  id="friday-14"
                  value="friday-14"
                  onChange={handleChange}
                  checked={isChecked('friday-14')}
                />
              </td>
            </tr>
            <tr>
              <td>15:00</td>
              <td>
                <input
                  key="46"
                  type="checkbox"
                  id="monday-15"
                  value="monday-15"
                  onChange={handleChange}
                  checked={isChecked('monday-15')}
                />
              </td>
              <td>
                <input
                  key="47"
                  type="checkbox"
                  id="tuesday-15"
                  value="tuesday-15"
                  onChange={handleChange}
                  checked={isChecked('tuesday-15')}
                />
              </td>
              <td>
                <input
                  key="48"
                  type="checkbox"
                  id="wednesday-15"
                  value="wednesday-15"
                  onChange={handleChange}
                  checked={isChecked('wednesday-15')}
                />
              </td>
              <td>
                <input
                  key="49"
                  type="checkbox"
                  id="thursday-15"
                  value="thursday-15"
                  onChange={handleChange}
                  checked={isChecked('thursday-15')}
                />
              </td>
              <td>
                <input
                  key="50"
                  type="checkbox"
                  id="friday-15"
                  value="friday-15"
                  onChange={handleChange}
                  checked={isChecked('friday-15')}
                />
              </td>
            </tr>
            <tr>
              <td>16:00</td>
              <td>
                <input
                  key="51"
                  type="checkbox"
                  id="monday-16"
                  value="monday-16"
                  onChange={handleChange}
                  checked={isChecked('monday-16')}
                />
              </td>
              <td>
                <input
                  key="52"
                  type="checkbox"
                  id="tuesday-16"
                  value="tuesday-16"
                  onChange={handleChange}
                  checked={isChecked('tuesday-16')}
                />
              </td>
              <td>
                <input
                  key="53"
                  type="checkbox"
                  id="wednesday-16"
                  value="wednesday-16"
                  onChange={handleChange}
                  checked={isChecked('wednesday-16')}
                />
              </td>
              <td>
                <input
                  key="54"
                  type="checkbox"
                  id="thursday-16"
                  value="thursday-16"
                  onChange={handleChange}
                  checked={isChecked('thursday-16')}
                />
              </td>
              <td>
                <input
                  key="55"
                  type="checkbox"
                  id="friday-16"
                  value="friday-16"
                  onChange={handleChange}
                  checked={isChecked('friday-16')}
                />
              </td>
            </tr>
            <tr>
              <td>17:00</td>
              <td>
                <input
                  key="56"
                  type="checkbox"
                  id="monday-17"
                  value="monday-17"
                  onChange={handleChange}
                  checked={isChecked('monday-17')}
                />
              </td>
              <td>
                <input
                  key="57"
                  type="checkbox"
                  id="tuesday-17"
                  value="tuesday-17"
                  onChange={handleChange}
                  checked={isChecked('tuesday-17')}
                />
              </td>
              <td>
                <input
                  key="58"
                  type="checkbox"
                  id="wednesday-17"
                  value="wednesday-17"
                  onChange={handleChange}
                  checked={isChecked('wednesday-17')}
                />
              </td>
              <td>
                <input
                  key="59"
                  type="checkbox"
                  id="thursday-17"
                  value="thursday-17"
                  onChange={handleChange}
                  checked={isChecked('thursday-17')}
                />
              </td>
              <td>
                <input
                  key="60"
                  type="checkbox"
                  id="friday-17"
                  value="friday-17"
                  onChange={handleChange}
                  checked={isChecked('friday-17')}
                />
              </td>
            </tr>
            <tr>
              <td>18:00</td>
              <td>
                <input
                  key="61"
                  type="checkbox"
                  id="monday-18"
                  value="monday-18"
                  onChange={handleChange}
                  checked={isChecked('monday-18')}
                />
              </td>
              <td>
                <input
                  key="62"
                  type="checkbox"
                  id="tuesday-18"
                  value="tuesday-18"
                  onChange={handleChange}
                  checked={isChecked('tuesday-18')}
                />
              </td>
              <td>
                <input
                  key="63"
                  type="checkbox"
                  id="wednesday-18"
                  value="wednesday-18"
                  onChange={handleChange}
                  checked={isChecked('wednesday-18')}
                />
              </td>
              <td>
                <input
                  key="64"
                  type="checkbox"
                  id="thursday-18"
                  value="thursday-18"
                  onChange={handleChange}
                  checked={isChecked('thursday-18')}
                />
              </td>
              <td>
                <input
                  key="65"
                  type="checkbox"
                  id="friday-18"
                  value="friday-18"
                  onChange={handleChange}
                  checked={isChecked('friday-18')}
                />
              </td>
            </tr>
            <tr>
              <td>19:00</td>
              <td>
                <input
                  key="66"
                  type="checkbox"
                  id="monday-19"
                  value="monday-19"
                  onChange={handleChange}
                  checked={isChecked('monday-19')}
                />
              </td>
              <td>
                <input
                  key="67"
                  type="checkbox"
                  id="tuesday-19"
                  value="tuesday-19"
                  onChange={handleChange}
                  checked={isChecked('tuesday-19')}
                />
              </td>
              <td>
                <input
                  key="68"
                  type="checkbox"
                  id="wednesday-19"
                  value="wednesday-19"
                  onChange={handleChange}
                  checked={isChecked('wednesday-19')}
                />
              </td>
              <td>
                <input
                  key="69"
                  type="checkbox"
                  id="thursday-19"
                  value="thursday-19"
                  onChange={handleChange}
                  checked={isChecked('thursday-19')}
                />
              </td>
              <td>
                <input
                  key="70"
                  type="checkbox"
                  id="friday-19"
                  value="friday-19"
                  onChange={handleChange}
                  checked={isChecked('friday-19')}
                />
              </td>
            </tr>
            <tr>
              <td>20:00</td>
              <td>
                <input
                  key="71"
                  type="checkbox"
                  id="monday-20"
                  value="monday-20"
                  onChange={handleChange}
                  checked={isChecked('monday-20')}
                />
              </td>
              <td>
                <input
                  key="72"
                  type="checkbox"
                  id="tuesday-20"
                  value="tuesday-20"
                  onChange={handleChange}
                  checked={isChecked('tuesday-20')}
                />
              </td>
              <td>
                <input
                  key="73"
                  type="checkbox"
                  id="wednesday-20"
                  value="wednesday-20"
                  onChange={handleChange}
                  checked={isChecked('wednesday-20')}
                />
              </td>
              <td>
                <input
                  key="74"
                  type="checkbox"
                  id="thursday-20"
                  value="thursday-20"
                  onChange={handleChange}
                  checked={isChecked('thursday-20')}
                />
              </td>
              <td>
                <input
                  key="75"
                  type="checkbox"
                  id="friday-20"
                  value="friday-20"
                  onChange={handleChange}
                  checked={isChecked('friday-20')}
                />
              </td>
            </tr>
          </tbody>
        </table>
        <div className={styles.bottomBtns}>
          <Button type="submit" onClick={onSubmit} />
        </div>
      </div>
    </section>
  );
}

export default AvailabilityForm;
