export const TEST_ADMIN = 'TEST_ADMIN';
export const GET_PSYCHOLOGIST_FETCHING = 'GET_PSYCHOLOGIST_FETCHING';
export const GET_PSYCHOLOGIST_FULFILLED = 'GET_PSYCHOLOGIST_FULFILLED';
export const GET_PSYCHOLOGIST_REJECTED = 'GET_PSYCHOLOGIST_REJECTED';
